name: Code Coverage
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov coverage
        pip install -r requirements.txt

    - name: Cleanup MongoDB container
      run: |
        if [ "$(docker ps -aq -f name=mongodb)" ]; then
          docker rm -f mongodb || true
        fi

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Run the tests and collect coverage
      run: |
        # Start the application in production mode in the background
        nohup FLASK_ENV=production python application.py > app.log 2>&1 &
        app_pid=$!

        # Allow the application to initialize
        sleep 10

        # Run tests and collect coverage
        echo "Running tests..."
        coverage run -m unittest tests.test_module > test_output.log 2>&1
        exit_code=$?

        # Generate reports if tests passed
        if [ $exit_code -eq 0 ]; then
          coverage xml -i
          coverage report -m
        else
          echo "Tests failed. Check the logs below:"
        fi

        # Print application and test logs
        echo "Application logs:"
        cat app.log
        echo "Test output logs:"
        cat test_output.log

        # Stop the application
        kill $app_pid || true

        exit $exit_code