name: Code Coverage
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov coverage
        pip install -r requirements.txt

    - name: Cleanup MongoDB container
      run: |
        if [ "$(docker ps -aq -f name=mongodb)" ]; then
          docker rm -f mongodb || true
        fi

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Run the tests and collect coverage
      run: |
        python application.py &  # Start the application in the background
        app_pid=$!  # Capture the application's PID
        sleep 5  # Allow the app to initialize

        echo "Running tests..."
        coverage run -m unittest discover tests > test_output.log 2>&1
        test_exit_code=$?  # Capture the test command's exit code

        # Stop the application process
        if ps -p $app_pid > /dev/null; then
          kill $app_pid
        fi

        # Display the test logs
        cat test_output.log

        # Generate coverage report if tests passed
        if [ $test_exit_code -eq 0 ]; then
          coverage xml -i
          coverage report -m
        fi

        exit $test_exit_code  # Fail the job if tests failed